kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubewarden
  namespace: fleet-default
spec:
  repo: ssh://git@github.com:rancherfederal/bullpen.git

  # To target specific clusters, uncomment this block
  # targets:
  # - name: example
  #   clusterSelector:
  #     matchLabels:
  #       cluster: example

  paths:
  - "./security/kubewarden/helm/crds"
  - "./security/kubewarden/helm/controllers"
  - "./security/kubewarden/helm/defaults"
